### ISSUE TITLE
FR: Printer definitions and usage in config files

### ISSUE THREAD

**Issue by GijsvanDulmen** [GijsvanDulmen/PlaterFlow#4]
Like the profiles we also want to point to a printer definition for uploading stuff. So we can have a single baseconfig with printer and profile definitions.

**Comment by GijsvanDulmen** [comment]
And use the SuperSlicer profiles itself to figure out the location of the printer? Can we use SuperSlicer for uploading as well?

**Comment by LeandroMarceddu** [comment]
We can use their superslicer configured /physical_printer/ folder if they wanna specify it.

Example: %APPDATA/SuperSlicer/physical_printer/Annex K3.ini (on Windows, in my case)
Contains: 
```
# generated by SuperSlicer 2.3.57 on 2021-10-17 at 13:18:31 UTC
host_type = klipper
preset_name = K3
print_host = 192.168.0.248
printer_technology = FFF
printhost_apikey = adfasdfsefasdfe
printhost_authorization_type = key
printhost_cafile = 
printhost_password = 
printhost_port = 
printhost_user = 
``` 


We would only need print_host. Apikey and the rest is only necessary for octoprint which I'm not sure if we are going to support or not.

**Comment by GijsvanDulmen** [comment]
https://github.com/platerflow/PlaterFlow/commit/32cc75dcf624b112af939598d2d5dab1f880dac1
